- name: Fetch and filter GitHub branches, then query Jira
  hosts: localhost
  gather_facts: no
  vars:
    jira_base_url: "https://davidaustinthatcher.atlassian.net" 
    jira_api_token: ""
    jira_user_email: "david.austin.thatcher@gmail.com"
    branch_prefix: "SCRUM-1"  # Prefix to search for in GitHub branches

  tasks:
    - name: Clone GitHub Repository
      git:
        repo: "https://github.com/dathatcher/HelloWorld.git"
        dest: "/tmp/github_repo"
        force: yes
      register: repo_clone

    - name: Fetch all remote branches
      shell: |
        cd /tmp/github_repo
        git fetch --all --prune
        git branch -r | sed 's/origin\///g' | awk '{$1=$1;print}'
      register: branch_list

    - name: Debug - Show Raw Branch Output
      debug:
        msg: "{{ branch_list.stdout_lines }}"

    - name: Extract Jira Ticket Number from Matching Branches
      set_fact:
        jira_tickets: "{{ branch_list.stdout_lines | select('search', '^' + branch_prefix) | map('regex_replace', '^' + branch_prefix + '(\\d+).*', branch_prefix + '\\1') | list }}"

    - name: Display Extracted Jira Ticket Numbers
      debug:
        msg: "Extracted Jira Tickets: {{ jira_tickets }}"

    - name: Fetch Jira Ticket Data for Each Extracted Ticket
      uri:
        url: "{{ jira_base_url }}/rest/api/2/issue/{{ item }}"
        method: GET
        headers:
          Authorization: "Basic {{ (jira_user_email + ':' + jira_api_token) | b64encode }}"
          Accept: "application/json"
        return_content: yes
      register: jira_response
      loop: "{{ jira_tickets }}"
      when: jira_tickets | length > 0

    - name: Display Jira Ticket Details
      debug:
        msg: "Ticket: {{ item.json.key }} | Status: {{ item.json.fields.status.name }} | Summary: {{ item.json.fields.summary }}"
      loop: "{{ jira_response.results }}"
      when: jira_tickets | length > 0
