- name: Fetch and filter GitHub branches
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clone GitHub Repository
      git:
        repo: "https://github.com/dathatcher/HelloWorld.git"
        dest: "/tmp/github_repo"
        force: yes
      register: repo_clone

    - name: Fetch all branches
      shell: "cd /tmp/github_repo && git branch -r | sed 's/origin\\///g'"
      register: branch_list

    - name: Filter branches starting with 'Dave'
      set_fact:
        dave_branches: "{{ branch_list.stdout_lines | select('search', '^dathatch') | list }}"

    - name: Display Matching Branches
      debug:
        msg: "Branches starting with 'Dave': {{ dave_branches }}"

    - name: Process Each Matching Branch
      shell: "cd /tmp/github_repo && git checkout {{ item }} && echo 'Processing branch: {{ item }}'"
      loop: "{{ dave_branches }}"
      when: dave_branches | length > 0
