- name: Fetch Public GitHub Repo Details
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clone GitHub Repo (Public)
      git:
        repo: "https://github.com/dathatcher/HelloWorld.git"
        dest: "/tmp/github_repo"
        version: "main"
        force: yes

    - name: Get Latest Commit Hash
      shell: "cd /tmp/github_repo && git rev-parse HEAD"
      register: latest_commit

    - name: Display Latest Commit Hash
      debug:
        msg: "Latest commit in main branch: {{ latest_commit.stdout }}"
