- name: Webhook-Triggered PR Merge - Query Jira and Send Email
  hosts: localhost
  gather_facts: no
  vars_files:
    - vault.yml  # Load encrypted secrets from Ansible Vault

  vars:
    jira_base_url: "https://davidaustinthatcher.atlassian.net"
    branch_prefix: "SCRUM-"  # Prefix to identify Jira ticket numbers in branch names
    custom_field_id: "customfield_10039"
    email_recipient: "{{ lookup('env', 'TO_EMAIL') }}"  # Email recipient from environment variable
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    smtp_username: "{{ jira_user_email }}"

  tasks:
    - name: Extract PR Branch and Merge Status from Webhook
      set_fact:
        pr_branch: "{{ lookup('vars', 'webhook_payload.pull_request.head.ref') }}"
        merged_branch: "{{ lookup('vars', 'webhook_payload.pull_request.base.ref') }}"
        pr_merged: "{{ lookup('vars', 'webhook_payload.pull_request.merged') | default(False) }}"

    - name: Debug - Show Extracted Branch Info
      debug:
        msg: "PR Branch: {{ pr_branch }} | Merged Into: {{ merged_branch }} | Merged: {{ pr_merged }}"

    - name: Proceed only if PR was merged into QA
      fail:
        msg: "This PR was not merged into QA, skipping execution."
      when: merged_branch != "QA" or not pr_merged

    - name: Extract Jira Ticket Number from PR Branch
      set_fact:
        jira_ticket: "{{ pr_branch | regex_replace('^' + branch_prefix + '(\\d+).*', branch_prefix + '\\1') }}"

    - name: Fetch Jira Ticket Data
      uri:
        url: "{{ jira_base_url }}/rest/api/2/issue/{{ jira_ticket }}"
        method: GET
        headers:
          Authorization: "Basic {{ (jira_user_email + ':' + jira_api_token) | b64encode }}"
          Accept: "application/json"
        return_content: yes
      register: jira_response
      when: jira_ticket is not none

    - name: Extract DB Object Value
      set_fact:
        db_object: "{{ jira_response.json.fields[custom_field_id] | default('') }}"
      when: jira_ticket is not none

    - name: Check if DB Object is Set
      set_fact:
        send_email: "{{ db_object | length > 0 }}"
      when: jira_ticket is not none

    - name: Send Email with Jira DB Object Information
      mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_recipient }}"
        subject: "{{ jira_ticket }} - DB Objects Request push to QA"
        body: |
          DB Team, 
          
          The following DB Objects for Jira ticket {{ jira_ticket }} are required to be pushed to QA:

          Ticket: {{ jira_ticket }}

          Link to Ticket: https://davidaustinthatcher.atlassian.net/browse/{{ jira_ticket }}

          DB Object Value: {{ db_object }}

          This is an automated message from Ansible.
        subtype: plain
        secure: starttls
      when: send_email | default(false)
