name: Run Ansible Playbook on PR Merge to QA

on:
  pull_request:
    branches:
      - "QA"  # Triggers when a PR is merged into QA
    types:
      - closed  # Ensures this only runs when PR is merged, not just created

jobs:
  run-ansible-playbook:
    if: github.event.pull_request.merged == true  # Ensures action runs only on merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          ansible-playbook -i "localhost," --connection=local combined_fetch_jira_v4.yml
